# Generated by Django 4.2.21 on 2025-06-04 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='col',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
