# Generated by Django 4.2.21 on 2025-06-04 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_timesheet_col_timesheet_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='col',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='row',
        ),
    ]
