# Generated by Django 4.2.21 on 2025-06-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_remove_timesheet_col_remove_timesheet_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
