# Generated by Django 4.2.21 on 2025-06-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_timesheet_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
